//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpreadTrader.Properties
{


	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
	internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
	{

		private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

		public static Settings Default
		{
			get
			{
				return defaultInstance;
			}
		}
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double ColumnWidth
        {
            get
            {
                return ((double)(this["ColumnWidth"]));
            }
            set
            {
                this["ColumnWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BFUser
        {
            get
            {
                return ((string)(this["BFUser"]));
            }
            set
            {
                this["BFUser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BFPassword
        {
            get
            {
                return ((string)(this["BFPassword"]));
            }
            set
            {
                this["BFPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CtrlLCBack
        {
            get
            {
                return ((int)(this["CtrlLCBack"]));
            }
            set
            {
                this["CtrlLCBack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LCBack
        {
            get
            {
                return ((int)(this["LCBack"]));
            }
            set
            {
                this["LCBack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RCBack
        {
            get
            {
                return ((int)(this["RCBack"]));
            }
            set
            {
                this["RCBack"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LCLay
        {
            get
            {
                return ((int)(this["LCLay"]));
            }
            set
            {
                this["LCLay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CtrlLCLay
        {
            get
            {
                return ((int)(this["CtrlLCLay"]));
            }
            set
            {
                this["CtrlLCLay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RCLay
        {
            get
            {
                return ((int)(this["RCLay"]));
            }
            set
            {
                this["RCLay"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Top
        {
            get
            {
                return ((double)(this["Top"]));
            }
            set
            {
                this["Top"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double Left
        {
            get
            {
                return ((double)(this["Left"]));
            }
            set
            {
                this["Left"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double Height
        {
            get
            {
                return ((double)(this["Height"]));
            }
            set
            {
                this["Height"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Width
        {
            get
            {
                return ((double)(this["Width"]));
            }
            set
            {
                this["Width"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Maximised
        {
            get
            {
                return ((bool)(this["Maximised"]));
            }
            set
            {
                this["Maximised"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.29")]
        public double back3
        {
            get
            {
                return ((double)(this["back3"]));
            }
            set
            {
                this["back3"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.89")]
        public double back2
        {
            get
            {
                return ((double)(this["back2"]));
            }
            set
            {
                this["back2"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LiveBets
        {
            get
            {
                return ((bool)(this["LiveBets"]));
            }
            set
            {
                this["LiveBets"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDUser
        {
            get
            {
                return ((string)(this["BDUser"]));
            }
            set
            {
                this["BDUser"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BDPassword
        {
            get
            {
                return ((string)(this["BDPassword"]));
            }
            set
            {
                this["BDPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowLive
        {
            get
            {
                return ((bool)(this["ShowLive"]));
            }
            set
            {
                this["ShowLive"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://p4-7006.uk2net.com/sangster/x.xml")]
        public string XMLPath
        {
            get
            {
                return ((string)(this["XMLPath"]));
            }
            set
            {
                this["XMLPath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RememberPasswords
        {
            get
            {
                return ((bool)(this["RememberPasswords"]));
            }
            set
            {
                this["RememberPasswords"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SessionToken
        {
            get
            {
                return ((string)(this["SessionToken"]));
            }
            set
            {
                this["SessionToken"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("uCmjo7RlVUJRCc0T")]
        public string AppKey
        {
            get
            {
                return ((string)(this["AppKey"]));
            }
            set
            {
                this["AppKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\client-2048.p12")]
        public string CertFile
        {
            get
            {
                return ((string)(this["CertFile"]));
            }
            set
            {
                this["CertFile"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zzzz2222")]
        public string CertPassword
        {
            get
            {
                return ((string)(this["CertPassword"]));
            }
            set
            {
                this["CertPassword"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Upgraded
        {
            get
            {
                return ((bool)(this["Upgraded"]));
            }
            set
            {
                this["Upgraded"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int WaitBF
        {
            get
            {
                return ((int)(this["WaitBF"]));
            }
            set
            {
                this["WaitBF"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int WaitBQ
        {
            get
            {
                return ((int)(this["WaitBQ"]));
            }
            set
            {
                this["WaitBQ"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Chartreuse")]
        public string BetfairSPColour
        {
            get
            {
                return ((string)(this["BetfairSPColour"]));
            }
            set
            {
                this["BetfairSPColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightSkyBlue")]
        public string BetdaqSPColour
        {
            get
            {
                return ((string)(this["BetdaqSPColour"]));
            }
            set
            {
                this["BetdaqSPColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Magenta")]
        public string MultiSPColour
        {
            get
            {
                return ((string)(this["MultiSPColour"]));
            }
            set
            {
                this["MultiSPColour"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LayTheField
        {
            get
            {
                return ((bool)(this["LayTheField"]));
            }
            set
            {
                this["LayTheField"] = value;
            }
        }
    }
}
